[package]
name = "truck-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
steamworks = "0.12.2"
windows = { version = "0.61.3", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_Threading",
] }
